#######################
# Hakobiya Server Config
#######################
[server]
name = "QA+"
bind = "localhost:8080"
path = "/ws"

[api]
enabled = true
path = "/api"
key = "abcdefg"
#allowedIPs = ["127.0.0.1"]

#######################
# Q: Question channel
#######################
[[channel]]
prefix = "Q"
expose = ["$listeners"] #Q.$listeners
	# Broadcasts
	[channel.broadcast]
		# Q.#answer - new answer notifications
		[channel.broadcast.answer]
			type = "string"
			readonly = true
	# Variables
	[channel.var]
		# Q.%typing - am I typing?
		[channel.var.typing]
			type = "bool"
	# Magic
	[channel.magic]
		# Q.&typers - how many users are typing
		[channel.magic.typers]
			var = "typing"
			map = "sum"
		[channel.magic.is_someone_typing]
			var = "typing"
			map = "any"

#######################
# @: User notifcations  
#######################
[[channel]]
prefix = "@"
restrict = ["userid"]
	# @.last_notify - last notification ID
	[channel.var.last_notify]
		type = "date"
		readonly = true