#######################
# Hakobiya Server Config
#######################
[server]
name = "Test Server"
bind = ":8080"
path = "/ws"

[static] # static file server
enabled = true
index = "test.html"
dirs = ["js"]

[api]
enabled = true
path = "/api"
key = "abcdefg"
#allowedIPs = ["127.0.0.1"]

#######################
# 話: Chat room
#######################
[[channel]]
prefix = "話"
expose = ["$listeners"]
[channel.var.name]
	type = "string"
	default = "Guest-%d"
[channel.magic.same_name]
	src = "%name"
	func = "same"
[channel.magic.has_bob]
	src = "%name"
	func = "any"
	[channel.magic.has_bob.params]
		value = "Bob"
[channel.magic.guest_pct]
	src = "%name"
	func = "percent"
	param = "Guest"
[channel.wire.chat]
	[channel.wire.chat.input]
		type = "string"
	[channel.wire.chat.output]
		[channel.wire.chat.output.rewrite]
			name = "%name" #c.%name
			msg = "$input"
			test = "'literal"



#######################
# Q: Question channel
#######################
[[channel]]
prefix = "Q"
expose = ["$listeners"] #Q.$listeners
# Broadcasts
[channel.broadcast]
	# Q.#answer - new answer notifications
	[channel.broadcast.answer]
		type = "string"
# Variables
[channel.var]
	# Q.%typing - am I typing?
	[channel.var.typing]
		type = "bool"
# Magic
[channel.magic]
	# Q.&typers - how many users are typing
	[channel.magic.typers]
		src = "%typing"
		func = "count"
	[channel.magic.is_someone_typing]
		src = "%typing"
		func = "any"