#######################
# Hakobiya Server Config
#######################
[server]
name = "Test Server"
bind = ":8080"
path = "/ws"

[api]
enabled = true
path = "/api"
key = "abcdefg"
#allowedIPs = ["127.0.0.1"]

#######################
# C: Chat room
#######################
[[channel]]
prefix = "c"
expose = ["$listeners"]
	[channel.var.name]
		type = "string"
		default = "Guest-%d"
	[channel.wire.chat]
		[channel.wire.chat.input]
			type = "string"
		[channel.wire.chat.output]
			type = "object"
			[channel.wire.chat.output.rewrite]
				name = "%name" #c.%name
				msg = "$input"
				test = "'literal"



#######################
# Q: Question channel
#######################
[[channel]]
prefix = "Q"
expose = ["$listeners"] #Q.$listeners
	# Broadcasts
	[channel.broadcast]
		# Q.#answer - new answer notifications
		[channel.broadcast.answer]
			type = "string"
			readonly = true
	# Variables
	[channel.var]
		# Q.%typing - am I typing?
		[channel.var.typing]
			type = "bool"
	# Magic
	[channel.magic]
		# Q.&typers - how many users are typing
		[channel.magic.typers]
			src = "%typing"
			func = "sum"
		[channel.magic.is_someone_typing]
			src = "%typing"
			func = "any"

#######################
# @: User notifcations  
#######################
[[channel]]
prefix = "@"
restrict = ["userid"]
	# @.last_notify - last notification ID
	[channel.var.last_notify]
		type = "date"
		readonly = true